/*
 * HPS IRQ IDs
 * ---------------
 * Description:
 * This file contains an enum type for various peripheral
 * interrupt IDs in the Leeds SoC Computer and Cyclone V HPS.
 *
 */

#ifndef HPS_IRQ_IDS_H_
#define HPS_IRQ_IDS_H_


typedef enum {

/* ARM A9 MPCORE devices (there are many; only a few are defined below) */
    IRQ_MPCORE_GLOBAL_TIMER         = 27,
    IRQ_MPCORE_PRIVATE_TIMER        = 29,
    IRQ_MPCORE_WATCHDOG             = 30,
    
/* ARM A9 CPU Interrupts (there are 40 in total; you shouldn't need any of them)*/
    IRQ_CPU0_PARITYFAIL             = 32,
    IRQ_CPU0_PARITYFAIL_BTAC        = 33,
    IRQ_CPU0_PARITYFAIL_GHB         = 34,
    IRQ_CPU0_PARITYFAIL_I_TAG       = 35,
    IRQ_CPU0_PARITYFAIL_I_DATA      = 36,
    IRQ_CPU0_PARITYFAIL_TLB         = 37,
    IRQ_CPU0_PARITYFAIL_D_OUTER     = 38,
    IRQ_CPU0_PARITYFAIL_D_TAG       = 39,
    IRQ_CPU0_PARITYFAIL_D_DATA      = 40,
    IRQ_CPU0_DEFLAGS0               = 41,
    IRQ_CPU0_DEFLAGS1               = 42,
    IRQ_CPU0_DEFLAGS2               = 43,
    IRQ_CPU0_DEFLAGS3               = 44,
    IRQ_CPU0_DEFLAGS4               = 45,
    IRQ_CPU0_DEFLAGS5               = 46,
    IRQ_CPU0_DEFLAGS6               = 47,
    IRQ_CPU1_PARITYFAIL             = 48,
    IRQ_CPU1_PARITYFAIL_BTAC        = 49,
    IRQ_CPU1_PARITYFAIL_GHB         = 50,
    IRQ_CPU1_PARITYFAIL_I_TAG       = 51,
    IRQ_CPU1_PARITYFAIL_I_DATA      = 52,
    IRQ_CPU1_PARITYFAIL_TLB         = 53,
    IRQ_CPU1_PARITYFAIL_D_OUTER     = 54,
    IRQ_CPU1_PARITYFAIL_D_TAG       = 55,
    IRQ_CPU1_PARITYFAIL_D_DATA      = 56,
    IRQ_CPU1_DEFLAGS0               = 57,
    IRQ_CPU1_DEFLAGS1               = 58,
    IRQ_CPU1_DEFLAGS2               = 59,
    IRQ_CPU1_DEFLAGS3               = 60,
    IRQ_CPU1_DEFLAGS4               = 61,
    IRQ_CPU1_DEFLAGS5               = 62,
    IRQ_CPU1_DEFLAGS6               = 63,
    IRQ_SCU_PARITYFAIL0             = 64,
    IRQ_SCU_PARITYFAIL1             = 65,
    IRQ_SCU_EV_ABORT                = 66,
    IRQ_L2_ECC_BYTE_WR              = 67,
    IRQ_L2_ECC_CORRECTED            = 68,
    IRQ_L2_ECC_UNCORRECTED          = 69,
    IRQ_L2_COMBINED                 = 70,
    IRQ_DDR_ECC_ERROR               = 71,

/* FPGA interrupts (there are 64 in total; Some have aliases for Leeds SoC Computer) */
    IRQ_INTERVAL_TIMER              = 72, // IRQ_FPGA0  = 72,
    IRQ_LSC_KEYS                    = 73, // IRQ_FPGA1  = 73,
    IRQ_FPGA2                       = 74,
    IRQ_FPGA3                       = 75,
    IRQ_FPGA4                       = 76,
    IRQ_FPGA5                       = 77,
    IRQ_LSC_AUDIO                   = 78, // IRQ_FPGA6  = 78,
    IRQ_LSC_PS2_PRIMARY             = 79, // IRQ_FPGA7  = 79,
    IRQ_LSC_JTAG                    = 80, // IRQ_FPGA8  = 80,
    IRQ_LSC_IrDA                    = 81, // IRQ_FPGA9  = 81,
    IRQ_FPGA10                      = 82,
    IRQ_LSC_GPIO_JP1                = 83, // IRQ_FPGA11 = 83,
    IRQ_LSC_GPIO_JP2                = 84, // IRQ_FPGA12 = 84,
    IRQ_FPGA13                      = 85,
    IRQ_FPGA14                      = 86,
    IRQ_FPGA15                      = 87,
    IRQ_FPGA16                      = 88,
    IRQ_LSC_PS2_SECONDARY           = 89, // IRQ_FPGA17 = 89,
    IRQ_FPGA18                      = 90,
    IRQ_FPGA19                      = 91,
    IRQ_FPGA20                      = 92,
    IRQ_FPGA21                      = 93,
    IRQ_FPGA22                      = 94,
    IRQ_FPGA23                      = 95,
    IRQ_FPGA24                      = 96,
    IRQ_FPGA25                      = 97,
    IRQ_FPGA26                      = 98,
    IRQ_FPGA27                      = 99,
    IRQ_FPGA28                      = 100,
    IRQ_FPGA29                      = 101,
    IRQ_FPGA30                      = 102,
    IRQ_FPGA31                      = 103,
    IRQ_FPGA32                      = 104,
    IRQ_FPGA33                      = 105,
    IRQ_FPGA34                      = 106,
    IRQ_FPGA35                      = 107,
    IRQ_FPGA36                      = 108,
    IRQ_FPGA37                      = 109,
    IRQ_FPGA38                      = 110,
    IRQ_FPGA39                      = 111,
    IRQ_FPGA40                      = 112,
    IRQ_FPGA41                      = 113,
    IRQ_FPGA42                      = 114,
    IRQ_FPGA43                      = 115,
    IRQ_FPGA44                      = 116,
    IRQ_FPGA45                      = 117,
    IRQ_FPGA46                      = 118,
    IRQ_FPGA47                      = 119,
    IRQ_FPGA48                      = 120,
    IRQ_FPGA49                      = 121,
    IRQ_FPGA50                      = 122,
    IRQ_FPGA51                      = 123,
    IRQ_FPGA52                      = 124,
    IRQ_FPGA53                      = 125,
    IRQ_FPGA54                      = 126,
    IRQ_FPGA55                      = 127,
    IRQ_FPGA56                      = 128,
    IRQ_FPGA57                      = 129,
    IRQ_FPGA58                      = 130,
    IRQ_FPGA59                      = 131,
    IRQ_FPGA60                      = 132,
    IRQ_FPGA61                      = 133,
    IRQ_FPGA62                      = 134,
    IRQ_FPGA63                      = 135,

/* HPS device interrupts (76 in total) */
    IRQ_DMA0                        = 136,
    IRQ_DMA1                        = 137,
    IRQ_DMA2                        = 138,
    IRQ_DMA3                        = 139,
    IRQ_DMA4                        = 140,
    IRQ_DMA5                        = 141,
    IRQ_DMA6                        = 142,
    IRQ_DMA7                        = 143,
    IRQ_DMA_ABORT                   = 144,
    IRQ_DMA_ECC_CORRECTED           = 145,
    IRQ_DMA_ECC_UNCORRECTED         = 146,
    IRQ_EMAC0                       = 147,
    IRQ_EMAC0_TX_ECC_CORRECTED      = 148,
    IRQ_EMAC0_TX_ECC_UNCORRECTED    = 149,
    IRQ_EMAC0_RX_ECC_CORRECTED      = 150,
    IRQ_EMAC0_RX_ECC_UNCORRECTED    = 151,
    IRQ_EMAC1                       = 152,
    IRQ_EMAC1_TX_ECC_CORRECTED      = 153,
    IRQ_EMAC1_TX_ECC_UNCORRECTED    = 154,
    IRQ_EMAC1_RX_ECC_CORRECTED      = 155,
    IRQ_EMAC1_RX_ECC_UNCORRECTED    = 156,
    IRQ_USB0                        = 157,
    IRQ_USB0_ECC_CORRECTED          = 158,
    IRQ_USB0_ECC_UNCORRECTED        = 159,
    IRQ_USB1                        = 160,
    IRQ_USB1_ECC_CORRECTED          = 161,
    IRQ_USB1_ECC_UNCORRECTED        = 162,
    IRQ_CAN0_STS                    = 163,
    IRQ_CAN0_MO                     = 164,
    IRQ_CAN0_ECC_CORRECTED          = 165,
    IRQ_CAN0_ECC_UNCORRECTED        = 166,
    IRQ_CAN1_STS                    = 167,
    IRQ_CAN1_MO                     = 168,
    IRQ_CAN1_ECC_CORRECTED          = 169,
    IRQ_CAN1_ECC_UNCORRECTED        = 170,
    IRQ_SDMMC                       = 171,
    IRQ_SDMMC_PORTA_ECC_CORRECTED   = 172,
    IRQ_SDMMC_PORTA_ECC_UNCORRECTED = 173,
    IRQ_SDMMC_PORTB_ECC_CORRECTED   = 174,
    IRQ_SDMMC_PORTB_ECC_UNCORRECTED = 175,
    IRQ_NAND                        = 176,
    IRQ_NANDR_ECC_CORRECTED         = 177,
    IRQ_NANDR_ECC_UNCORRECTED       = 178,
    IRQ_NANDW_ECC_CORRECTED         = 179,
    IRQ_NANDW_ECC_UNCORRECTED       = 180,
    IRQ_NANDE_ECC_CORRECTED         = 181,
    IRQ_NANDE_ECC_UNCORRECTED       = 182,
    IRQ_QSPI                        = 183,
    IRQ_QSPI_ECC_CORRECTED          = 184,
    IRQ_QSPI_ECC_UNCORRECTED        = 185,
    IRQ_SPI0                        = 186,
    IRQ_SPI1                        = 187,
    IRQ_SPI2                        = 188,
    IRQ_SPI3                        = 189,
    IRQ_I2C0                        = 190,
    IRQ_I2C1                        = 191,
    IRQ_I2C2                        = 192,
    IRQ_I2C3                        = 193,
    IRQ_UART0                       = 194,
    IRQ_UART1                       = 195,
    IRQ_GPIO0                       = 196,
    IRQ_GPIO1                       = 197,
    IRQ_GPIO2                       = 198,
    IRQ_TIMER_L4SP_0                = 199, //HPS Timer 0
    IRQ_TIMER_L4SP_1                = 200, //HPS Timer 1
    IRQ_TIMER_OSC1_0                = 201,
    IRQ_TIMER_OSC1_1                = 202,
    IRQ_WDOG0                       = 203, //HPS Watchdog 0
    IRQ_WDOG1                       = 204,
    IRQ_CLKMGR                      = 205,
    IRQ_MPUWAKEUP                   = 206,
    IRQ_FPGA_MAN                    = 207,
    IRQ_NCTIIRQ_0                   = 208,
    IRQ_NCTIIRQ_1                   = 209,
    IRQ_RAM_ECC_CORRECTED           = 210,
    IRQ_RAM_ECC_UNCORRECTED         = 211

} HPSIRQSource;



#endif /* HPS_IRQ_IDS_H_ */
